// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyI3qP-fWmqBn_FXbYgyXHPhd15QqciJ0',
    appId: '1:405061011142:web:74e8191d1cfa1fbb30b9c7',
    messagingSenderId: '405061011142',
    projectId: 'tracker-fa204',
    authDomain: 'tracker-fa204.firebaseapp.com',
    storageBucket: 'tracker-fa204.appspot.com',
    measurementId: 'G-ZH1RLL0HLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz8I6XfRP-qs5LO95-aVscRaiLY_xjLu0',
    appId: '1:405061011142:android:27633d57b5f2d26430b9c7',
    messagingSenderId: '405061011142',
    projectId: 'tracker-fa204',
    storageBucket: 'tracker-fa204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJMM2Z12YjYTKmoEHkwYTMF9A7Mq2udKY',
    appId: '1:405061011142:ios:31f0ab284c41dbc030b9c7',
    messagingSenderId: '405061011142',
    projectId: 'tracker-fa204',
    storageBucket: 'tracker-fa204.appspot.com',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJMM2Z12YjYTKmoEHkwYTMF9A7Mq2udKY',
    appId: '1:405061011142:ios:31f0ab284c41dbc030b9c7',
    messagingSenderId: '405061011142',
    projectId: 'tracker-fa204',
    storageBucket: 'tracker-fa204.appspot.com',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyI3qP-fWmqBn_FXbYgyXHPhd15QqciJ0',
    appId: '1:405061011142:web:bc92f0086fe4abb230b9c7',
    messagingSenderId: '405061011142',
    projectId: 'tracker-fa204',
    authDomain: 'tracker-fa204.firebaseapp.com',
    storageBucket: 'tracker-fa204.appspot.com',
    measurementId: 'G-X24S001K3Z',
  );

}